development:
  user: fedoraAdmin
  password: fedoraAdmin
  root_uri: http://127.0.0.1:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest/dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  root_uri: http://127.0.0.1:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest/test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  root_uri: http://127.0.0.1:8983/fedora/rest/prod
